name: Java CI

on:
  - push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '23.0.1'
          distribution: 'graalvm'
          architecture: x64

      - uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: '8.12'

      - name: Build and test
        run: make test-report

      - uses: qltysh/qlty-action/coverage@main
        with:
          coverage-token: ${{ secrets.QLTY_COVERAGE_TOKEN }}
          files: app/build/reports/jacoco/test/jacocoTestReport.xml
          add-prefix: app/src/main/java/






  


    
