name: Java CI

on:
  - push
  - pull_request

defaults:
  run:
    working-directory: app

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          architecture: x64

      - uses: gradle/gradle-build-action@v3
        with:
          gradle-version: 8.12
          arguments: build
          build-root-directory: app

      - name: Setup
        run: make setup

      - name: Build project
        run: make build

      - name: Checkstyle Main
        run: make checkstyleMain

      - name: Checkstyle Test
        run: make checkstyleTest

      - name: Tests
        run: make test

      - name: Report
        run: make report

      - uses: qltysh/qlty-action/coverage@main
        with:
          coverage-token: ${{ secrets.QLTY_COVERAGE_TOKEN }}
          files: build/reports/jacoco/test/jacocoTestReport.xml






  


    
